//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *EndpointPolicy) DeepCopyInto(out *EndpointPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *EndpointPolicy) DeepCopy() *EndpointPolicy {
	if in == nil {
		return nil
	}
	out := new(EndpointPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *EndpointPolicy) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *EndpointPolicyList) DeepCopyInto(out *EndpointPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EndpointPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *EndpointPolicyList) DeepCopy() *EndpointPolicyList {
	if in == nil {
		return nil
	}
	out := new(EndpointPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *EndpointPolicyList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *EndpointPolicySpec) DeepCopyInto(out *EndpointPolicySpec) {
	*out = *in
	out.AppRef = in.AppRef
	out.GatewayRef = in.GatewayRef
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]EndpointSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *EndpointPolicySpec) DeepCopy() *EndpointPolicySpec {
	if in == nil {
		return nil
	}
	out := new(EndpointPolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *EndpointPolicyStatus) DeepCopyInto(out *EndpointPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EndpointStatuses != nil {
		in, out := &in.EndpointStatuses, &out.EndpointStatuses
		*out = make([]EndpointStatus, len(*in))
		copy(*out, *in)
	}
}

func (in *EndpointPolicyStatus) DeepCopy() *EndpointPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *AppReference) DeepCopyInto(out *AppReference) {
	*out = *in
}

func (in *AppReference) DeepCopy() *AppReference {
	if in == nil {
		return nil
	}
	out := new(AppReference)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayReference) DeepCopyInto(out *GatewayReference) {
	*out = *in
}

func (in *GatewayReference) DeepCopy() *GatewayReference {
	if in == nil {
		return nil
	}
	out := new(GatewayReference)
	in.DeepCopyInto(out)
	return out
}

func (in *EndpointSpec) DeepCopyInto(out *EndpointSpec) {
	*out = *in
	out.Match = in.Match
	if in.CanaryWeight != nil {
		in, out := &in.CanaryWeight, &out.CanaryWeight
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSpec)
		**out = **in
	}
	if in.HPA != nil {
		in, out := &in.HPA, &out.HPA
		*out = new(HPASpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

func (in *EndpointSpec) DeepCopy() *EndpointSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *MatchSpec) DeepCopyInto(out *MatchSpec) {
	*out = *in
}

func (in *MatchSpec) DeepCopy() *MatchSpec {
	if in == nil {
		return nil
	}
	out := new(MatchSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
}

func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HPASpec) DeepCopyInto(out *HPASpec) {
	*out = *in
	if in.CPUTarget != nil {
		in, out := &in.CPUTarget, &out.CPUTarget
		*out = new(int32)
		**out = **in
	}
	if in.MemoryTarget != nil {
		in, out := &in.MemoryTarget, &out.MemoryTarget
		*out = new(int32)
		**out = **in
	}
}

func (in *HPASpec) DeepCopy() *HPASpec {
	if in == nil {
		return nil
	}
	out := new(HPASpec)
	in.DeepCopyInto(out)
	return out
}

func (in *EndpointStatus) DeepCopyInto(out *EndpointStatus) {
	*out = *in
}

func (in *EndpointStatus) DeepCopy() *EndpointStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointStatus)
	in.DeepCopyInto(out)
	return out
}
